/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package database.dto;

import com.spoledge.audao.db.dto.AbstractDto;

/**
 * This is a DTO class.
 *
 * @author generated
 */
public class Modalitet extends AbstractDto {

    ////////////////////////////////////////////////////////////////////////////
    // Static
    ////////////////////////////////////////////////////////////////////////////

    public static final String TABLE = "modalitet";

    ////////////////////////////////////////////////////////////////////////////
    // Attributes
    ////////////////////////////////////////////////////////////////////////////

    private Integer modalitetId;
    private String modalitetNavn;

    ////////////////////////////////////////////////////////////////////////////
    // Constructors
    ////////////////////////////////////////////////////////////////////////////

    /**
     * Creates a new empty DTO.
     */
    public Modalitet() {
    }

    ////////////////////////////////////////////////////////////////////////////
    // Public
    ////////////////////////////////////////////////////////////////////////////

    public Integer getModalitetId() {
        return modalitetId;
    }

    public void setModalitetId( Integer _val) {
        this.modalitetId = _val;
    }

    public String getModalitetNavn() {
        return modalitetNavn;
    }

    public void setModalitetNavn( String _val) {
        this.modalitetNavn = _val;
    }

    /**
     * Indicates whether some other object is "equal to" this one.
     * Uses 'columns' equality type.
     */
    @Override
    public boolean equals( Object _other ) {
        if (_other == this) return true;
        if (_other == null || (!(_other instanceof Modalitet))) return false;

        Modalitet _o = (Modalitet) _other;

        if ( modalitetId == null ) {
            if ( _o.modalitetId != null ) return false;
        }
        else if ( _o.modalitetId == null || modalitetId.intValue() != _o.modalitetId.intValue()) return false;

        if ( modalitetNavn == null ) {
            if ( _o.modalitetNavn != null ) return false;
        }
        else if ( _o.modalitetNavn == null || !modalitetNavn.equals( _o.modalitetNavn )) return false;

        return true;
    }

    /**
     * Returns a hash code value for the object.
     */
    @Override
    public int hashCode() {
        int _ret = -120555737; // = "Modalitet".hashCode()
        _ret += modalitetId == null ? 0 : modalitetId;
        _ret = 29 * _ret + (modalitetNavn == null ? 0 : modalitetNavn.hashCode());

        return _ret;
    }


    ////////////////////////////////////////////////////////////////////////////
    // Protected
    ////////////////////////////////////////////////////////////////////////////
		
    /**
     * Constructs the content for the toString() method.
     */
    protected void contentToString(StringBuffer sb) {
        append( sb, "modalitetId", modalitetId );
        append( sb, "modalitetNavn", modalitetNavn );
    }
}
