/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package database.dto;

import java.sql.Timestamp;

import com.spoledge.audao.db.dto.AbstractDto;

/**
 * This is a DTO class.
 *
 * @author generated
 */
public class Patient extends AbstractDto {

    ////////////////////////////////////////////////////////////////////////////
    // Static
    ////////////////////////////////////////////////////////////////////////////

    public static final String TABLE = "patient";

    ////////////////////////////////////////////////////////////////////////////
    // Attributes
    ////////////////////////////////////////////////////////////////////////////

    private Integer patientId;
    private String patientCpr;
    private String patientNavn;
    private String patientAdresse;
    private String patientTlf;
    private Timestamp foedselsdag;
    private String stamafdeling;

    ////////////////////////////////////////////////////////////////////////////
    // Constructors
    ////////////////////////////////////////////////////////////////////////////

    /**
     * Creates a new empty DTO.
     */
    public Patient() {
    }

    ////////////////////////////////////////////////////////////////////////////
    // Public
    ////////////////////////////////////////////////////////////////////////////

    public Integer getPatientId() {
        return patientId;
    }

    public void setPatientId( Integer _val) {
        this.patientId = _val;
    }

    public String getPatientCpr() {
        return patientCpr;
    }

    public void setPatientCpr( String _val) {
        this.patientCpr = _val;
    }

    public String getPatientNavn() {
        return patientNavn;
    }

    public void setPatientNavn( String _val) {
        this.patientNavn = _val;
    }

    public String getPatientAdresse() {
        return patientAdresse;
    }

    public void setPatientAdresse( String _val) {
        this.patientAdresse = _val;
    }

    public String getPatientTlf() {
        return patientTlf;
    }

    public void setPatientTlf( String _val) {
        this.patientTlf = _val;
    }

    public Timestamp getFoedselsdag() {
        return foedselsdag;
    }

    public void setFoedselsdag( java.util.Date _val ) {
        setFoedselsdag((Timestamp)( _val != null ? new Timestamp( _val.getTime()) : null ));
    }

    public void setFoedselsdag( Timestamp _val) {
        this.foedselsdag = _val;
    }

    public String getStamafdeling() {
        return stamafdeling;
    }

    public void setStamafdeling( String _val) {
        this.stamafdeling = _val;
    }

    /**
     * Indicates whether some other object is "equal to" this one.
     * Uses 'columns' equality type.
     */
    @Override
    public boolean equals( Object _other ) {
        if (_other == this) return true;
        if (_other == null || (!(_other instanceof Patient))) return false;

        Patient _o = (Patient) _other;

        if ( patientId == null ) {
            if ( _o.patientId != null ) return false;
        }
        else if ( _o.patientId == null || patientId.intValue() != _o.patientId.intValue()) return false;

        if ( patientCpr == null ) {
            if ( _o.patientCpr != null ) return false;
        }
        else if ( _o.patientCpr == null || !patientCpr.equals( _o.patientCpr )) return false;

        if ( patientNavn == null ) {
            if ( _o.patientNavn != null ) return false;
        }
        else if ( _o.patientNavn == null || !patientNavn.equals( _o.patientNavn )) return false;

        if ( patientAdresse == null ) {
            if ( _o.patientAdresse != null ) return false;
        }
        else if ( _o.patientAdresse == null || !patientAdresse.equals( _o.patientAdresse )) return false;

        if ( patientTlf == null ) {
            if ( _o.patientTlf != null ) return false;
        }
        else if ( _o.patientTlf == null || !patientTlf.equals( _o.patientTlf )) return false;

        if ( foedselsdag == null ) {
            if ( _o.foedselsdag != null ) return false;
        }
        else if ( _o.foedselsdag == null || foedselsdag.getTime() != _o.foedselsdag.getTime()) return false;

        if ( stamafdeling == null ) {
            if ( _o.stamafdeling != null ) return false;
        }
        else if ( _o.stamafdeling == null || !stamafdeling.equals( _o.stamafdeling )) return false;

        return true;
    }

    /**
     * Returns a hash code value for the object.
     */
    @Override
    public int hashCode() {
        int _ret = 873235173; // = "Patient".hashCode()
        _ret += patientId == null ? 0 : patientId;
        _ret = 29 * _ret + (patientCpr == null ? 0 : patientCpr.hashCode());
        _ret = 29 * _ret + (patientNavn == null ? 0 : patientNavn.hashCode());
        _ret = 29 * _ret + (patientAdresse == null ? 0 : patientAdresse.hashCode());
        _ret = 29 * _ret + (patientTlf == null ? 0 : patientTlf.hashCode());
        _ret = 29 * _ret + (foedselsdag == null ? 0 : (int)foedselsdag.getTime());
        _ret = 29 * _ret + (stamafdeling == null ? 0 : stamafdeling.hashCode());

        return _ret;
    }


    ////////////////////////////////////////////////////////////////////////////
    // Protected
    ////////////////////////////////////////////////////////////////////////////
		
    /**
     * Constructs the content for the toString() method.
     */
    protected void contentToString(StringBuffer sb) {
        append( sb, "patientId", patientId );
        append( sb, "patientCpr", patientCpr );
        append( sb, "patientNavn", patientNavn );
        append( sb, "patientAdresse", patientAdresse );
        append( sb, "patientTlf", patientTlf );
        append( sb, "foedselsdag", foedselsdag );
        append( sb, "stamafdeling", stamafdeling );
    }
}
