/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package database.dto;

import java.sql.Timestamp;

import com.spoledge.audao.db.dto.AbstractDto;

/**
 * This is a DTO class.
 *
 * @author generated
 */
public class Patient extends AbstractDto {

    ////////////////////////////////////////////////////////////////////////////
    // Static
    ////////////////////////////////////////////////////////////////////////////

    public static final String TABLE = "patient";

    ////////////////////////////////////////////////////////////////////////////
    // Attributes
    ////////////////////////////////////////////////////////////////////////////

    private String cpr;
    private Timestamp foedselsdag;
    private String afdeling;

    ////////////////////////////////////////////////////////////////////////////
    // Constructors
    ////////////////////////////////////////////////////////////////////////////

    /**
     * Creates a new empty DTO.
     */
    public Patient() {
    }

    ////////////////////////////////////////////////////////////////////////////
    // Public
    ////////////////////////////////////////////////////////////////////////////

    public String getCpr() {
        return cpr;
    }

    public void setCpr( String _val) {
        this.cpr = _val;
    }

    public Timestamp getFoedselsdag() {
        return foedselsdag;
    }

    public void setFoedselsdag( java.util.Date _val ) {
        setFoedselsdag((Timestamp)( _val != null ? new Timestamp( _val.getTime()) : null ));
    }

    public void setFoedselsdag( Timestamp _val) {
        this.foedselsdag = _val;
    }

    public String getAfdeling() {
        return afdeling;
    }

    public void setAfdeling( String _val) {
        this.afdeling = _val;
    }

    /**
     * Indicates whether some other object is "equal to" this one.
     * Uses 'columns' equality type.
     */
    @Override
    public boolean equals( Object _other ) {
        if (_other == this) return true;
        if (_other == null || (!(_other instanceof Patient))) return false;

        Patient _o = (Patient) _other;

        if ( cpr == null ) {
            if ( _o.cpr != null ) return false;
        }
        else if ( _o.cpr == null || !cpr.equals( _o.cpr )) return false;

        if ( foedselsdag == null ) {
            if ( _o.foedselsdag != null ) return false;
        }
        else if ( _o.foedselsdag == null || foedselsdag.getTime() != _o.foedselsdag.getTime()) return false;

        if ( afdeling == null ) {
            if ( _o.afdeling != null ) return false;
        }
        else if ( _o.afdeling == null || !afdeling.equals( _o.afdeling )) return false;

        return true;
    }

    /**
     * Returns a hash code value for the object.
     */
    @Override
    public int hashCode() {
        int _ret = 873235173; // = "Patient".hashCode()
        _ret += cpr == null ? 0 : cpr.hashCode();
        _ret = 29 * _ret + (foedselsdag == null ? 0 : (int)foedselsdag.getTime());
        _ret = 29 * _ret + (afdeling == null ? 0 : afdeling.hashCode());

        return _ret;
    }


    ////////////////////////////////////////////////////////////////////////////
    // Protected
    ////////////////////////////////////////////////////////////////////////////
		
    /**
     * Constructs the content for the toString() method.
     */
    protected void contentToString(StringBuffer sb) {
        append( sb, "cpr", cpr );
        append( sb, "foedselsdag", foedselsdag );
        append( sb, "afdeling", afdeling );
    }
}
