/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package database.dto;

import java.sql.Date;

import java.sql.Timestamp;

import com.spoledge.audao.db.dto.AbstractDto;

/**
 * This is a DTO class.
 *
 * @author generated
 */
public class RegisteredUser extends AbstractDto {

    ////////////////////////////////////////////////////////////////////////////
    // Static
    ////////////////////////////////////////////////////////////////////////////

    public static final String TABLE = "registered_users";

    ////////////////////////////////////////////////////////////////////////////
    // Attributes
    ////////////////////////////////////////////////////////////////////////////

    private Long userId;
    private String gaeUserId;
    private String userName;
    private Date createdDate;
    private Timestamp lastLoginDate;

    ////////////////////////////////////////////////////////////////////////////
    // Constructors
    ////////////////////////////////////////////////////////////////////////////

    /**
     * Creates a new empty DTO.
     */
    public RegisteredUser() {
    }

    ////////////////////////////////////////////////////////////////////////////
    // Public
    ////////////////////////////////////////////////////////////////////////////

    public Long getUserId() {
        return userId;
    }

    public void setUserId( Long _val) {
        this.userId = _val;
    }

    public String getGaeUserId() {
        return gaeUserId;
    }

    public void setGaeUserId( String _val) {
        this.gaeUserId = _val;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName( String _val) {
        this.userName = _val;
    }

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate( java.util.Date _val ) {
        setCreatedDate((Date)( _val != null ? new Date( _val.getTime()) : null ));
    }

    public void setCreatedDate( Date _val) {
        this.createdDate = _val;
    }

    public Timestamp getLastLoginDate() {
        return lastLoginDate;
    }

    public void setLastLoginDate( java.util.Date _val ) {
        setLastLoginDate((Timestamp)( _val != null ? new Timestamp( _val.getTime()) : null ));
    }

    public void setLastLoginDate( Timestamp _val) {
        this.lastLoginDate = _val;
    }

    /**
     * Indicates whether some other object is "equal to" this one.
     * Uses 'columns' equality type.
     */
    @Override
    public boolean equals( Object _other ) {
        if (_other == this) return true;
        if (_other == null || (!(_other instanceof RegisteredUser))) return false;

        RegisteredUser _o = (RegisteredUser) _other;

        if ( userId == null ) {
            if ( _o.userId != null ) return false;
        }
        else if ( _o.userId == null || userId.longValue() != _o.userId.longValue()) return false;

        if ( gaeUserId == null ) {
            if ( _o.gaeUserId != null ) return false;
        }
        else if ( _o.gaeUserId == null || !gaeUserId.equals( _o.gaeUserId )) return false;

        if ( userName == null ) {
            if ( _o.userName != null ) return false;
        }
        else if ( _o.userName == null || !userName.equals( _o.userName )) return false;

        if ( createdDate == null ) {
            if ( _o.createdDate != null ) return false;
        }
        else if ( _o.createdDate == null || createdDate.getTime() != _o.createdDate.getTime()) return false;

        if ( lastLoginDate == null ) {
            if ( _o.lastLoginDate != null ) return false;
        }
        else if ( _o.lastLoginDate == null || lastLoginDate.getTime() != _o.lastLoginDate.getTime()) return false;

        return true;
    }

    /**
     * Returns a hash code value for the object.
     */
    @Override
    public int hashCode() {
        int _ret = -983352947; // = "RegisteredUser".hashCode()
        _ret += userId == null ? 0 : (int)(userId ^ (userId >>> 32));
        _ret = 29 * _ret + (gaeUserId == null ? 0 : gaeUserId.hashCode());
        _ret = 29 * _ret + (userName == null ? 0 : userName.hashCode());
        _ret = 29 * _ret + (createdDate == null ? 0 : (int)createdDate.getTime());
        _ret = 29 * _ret + (lastLoginDate == null ? 0 : (int)lastLoginDate.getTime());

        return _ret;
    }


    ////////////////////////////////////////////////////////////////////////////
    // Protected
    ////////////////////////////////////////////////////////////////////////////
		
    /**
     * Constructs the content for the toString() method.
     */
    protected void contentToString(StringBuffer sb) {
        append( sb, "userId", userId );
        append( sb, "gaeUserId", gaeUserId );
        append( sb, "userName", userName );
        append( sb, "createdDate", createdDate );
        append( sb, "lastLoginDate", lastLoginDate );
    }
}
