/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package database.dao;

import java.sql.Date;
import java.sql.Timestamp;

import com.spoledge.audao.db.dao.AbstractDao;
import com.spoledge.audao.db.dao.DaoException;

import database.dto.MrKontrol;


/**
 * This is the DAO.
 *
 * @author generated
 */
public interface MrKontrolDao extends AbstractDao {

    /**
     * Finds a record identified by its primary key.
     * @return the record found or null
     */
    public MrKontrol findByPrimaryKey( int mrKontrolskemaId );

    /**
     * Inserts a new record.
     * @return the generated primary key - mrKontrolskemaId
     */
    public int insert( MrKontrol dto ) throws DaoException;

    /**
     * Updates column tidl_billed_diagnostik of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateTidlBilledDiagnostik( int mrKontrolskemaId, String tidlBilledDiagnostik ) throws DaoException;

    /**
     * Updates column pacemaker of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updatePacemaker( int mrKontrolskemaId, boolean pacemaker ) throws DaoException;

    /**
     * Updates column metal_implantater of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateMetalImplantater( int mrKontrolskemaId, boolean metalImplantater ) throws DaoException;

    /**
     * Updates column metal_implantater_beskrivelse of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateMetalImplantaterBeskrivelse( int mrKontrolskemaId, String metalImplantaterBeskrivelse ) throws DaoException;

    /**
     * Updates column andet_metalisk of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateAndetMetalisk( int mrKontrolskemaId, boolean andetMetalisk ) throws DaoException;

    /**
     * Updates column AndetMetalImplBeskrivelse of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateAndetMetalImplBeskrivelse( int mrKontrolskemaId, String metalImplantaterBeskrivelse ) throws DaoException;

    /**
     * Updates column nyresygdom of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateNyresygdom( int mrKontrolskemaId, boolean nyresygdom ) throws DaoException;

    /**
     * Updates column nyresygdom_beskrivelse of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateNyresygdomBeskrivelse( int mrKontrolskemaId, String nyresygdomBeskrivelse ) throws DaoException;

    /**
     * Updates column graviditet of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateGraviditet( int mrKontrolskemaId, Boolean graviditet ) throws DaoException;

    /**
     * Updates column graviditet_uge of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateGraviditetUge( int mrKontrolskemaId, Integer graviditetUge ) throws DaoException;

    /**
     * Updates column praep_forsyn of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updatePraepForsyn( int mrKontrolskemaId, String praepForsyn ) throws DaoException;

    /**
     * Updates column hoejde of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateHoejde( int mrKontrolskemaId, Integer hoejde ) throws DaoException;

    /**
     * Updates column vaegt of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateVaegt( int mrKontrolskemaId, Integer vaegt ) throws DaoException;

    /**
     * Updates column rekvirent_id of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateRekvirentId( int mrKontrolskemaId, Integer rekvirentId ) throws DaoException;

    /**
     * Updates column mr_boern of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateMrBoern( int mrKontrolskemaId, MrKontrol.MrBoern mrBoern ) throws DaoException;

    /**
     * Updates column mr_voksen of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateMrVoksen( int mrKontrolskemaId, MrKontrol.MrVoksen mrVoksen ) throws DaoException;

}
