/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package database.dao;

import com.spoledge.audao.db.dao.AbstractDao;
import com.spoledge.audao.db.dao.DaoException;

import database.dto.Patient;


/**
 * This is the DAO.
 *
 * @author generated
 */
public interface PatientDao extends AbstractDao {

    /**
     * Finds a record identified by its primary key.
     * @return the record found or null
     */
    public Patient findByPrimaryKey( int patientId );

    /**
     * Finds records.
     */
    public Patient[] findDynamic( String cond, int offset, int count, Object... params );

    /**
     * Inserts a new record.
     * @return the generated primary key - patientId
     */
    public int insert( Patient dto ) throws DaoException;

}
