/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package database.dao;

import java.sql.Timestamp;

import com.spoledge.audao.db.dao.AbstractDao;
import com.spoledge.audao.db.dao.DaoException;

import database.dto.PETCTKontrolskema;


/**
 * This is the DAO.
 *
 * @author generated
 */
public interface PETCTKontrolskemaDao extends AbstractDao {

    /**
     * Finds a record identified by its primary key.
     * @return the record found or null
     */
    public PETCTKontrolskema findByPrimaryKey( int pETCTKontrolskemaId );

    /**
     * Finds records.
     */
    public PETCTKontrolskema[] findDynamic( String cond, int offset, int count, Object... params );

    /**
     * Inserts a new record.
     * @return the generated primary key - pETCTKontrolskemaId
     */
    public int insert( PETCTKontrolskema dto ) throws DaoException;

    /**
     * Updates column preMed of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updatePreMed( int pETCTKontrolskemaId, Boolean preMed ) throws DaoException;

    /**
     * Updates column DMRegime of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateDMRegime( int pETCTKontrolskemaId, Boolean dMRegime ) throws DaoException;

    /**
     * Updates column POKontrast of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updatePOKontrast( int pETCTKontrolskemaId, Boolean pOKontrast ) throws DaoException;

    /**
     * Updates column IVKontrast of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateIVKontrast( int pETCTKontrolskemaId, Boolean iVKontrast ) throws DaoException;

    /**
     * Updates column AktuelPKreatinin of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateAktuelPKreatinin( int pETCTKontrolskemaId, Integer aktuelPKreatinin ) throws DaoException;

    /**
     * Updates column AktuelPKreatTimestamp of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateAktuelPKreatTimestamp( int pETCTKontrolskemaId, Timestamp aktuelPKreatTimestamp ) throws DaoException;

}
