/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package database.dao;

import java.sql.Date;
import java.sql.Timestamp;

import com.spoledge.audao.db.dao.AbstractDao;
import com.spoledge.audao.db.dao.DaoException;

import database.dto.RegisteredUser;


/**
 * This is the DAO.
 *
 * @author generated
 */
public interface RegisteredUserDao extends AbstractDao {

    /**
     * Finds a record identified by its primary key.
     * @return the record found or null
     */
    public RegisteredUser findByPrimaryKey( long userId );

    /**
     * Finds a record.
     */
    public RegisteredUser findByGaeUserId( String gaeUserId );

    /**
     * Inserts a new record.
     * @return the generated primary key - userId
     */
    public long insert( RegisteredUser dto ) throws DaoException;

    /**
     * Updates column last_login_date of one record found by primary key.
     * @return true iff the record was really updated (=found)
     */
    public boolean updateLastLoginDate( long userId, Timestamp lastLoginDate ) throws DaoException;

}
