/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package database.dao;

import com.spoledge.audao.db.dao.AbstractDao;
import com.spoledge.audao.db.dao.DaoException;

import database.dto.Rettigheder;


/**
 * This is the DAO.
 *
 * @author generated
 */
public interface RettighederDao extends AbstractDao {

    /**
     * Finds a record identified by its primary key.
     * @return the record found or null
     */
    public Rettigheder findByPrimaryKey( int rettighedsId );

    /**
     * Finds records.
     */
    public Rettigheder[] findDynamic( String cond, int offset, int count, Object... params );

    /**
     * Inserts a new record.
     * @return the generated primary key - rettighedsId
     */
    public int insert( Rettigheder dto ) throws DaoException;

    /**
     * Updates one record found by primary key.
     * @return true iff the record was really updated (=found and any change was really saved)
     */
    public boolean update( int rettighedsId, Rettigheder dto ) throws DaoException;

}
