/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package database.dao.mysql;

import java.sql.Connection;

import database.dao.*;


/**
 * This is the main implementation class for obtaining DAO objects.
 * @author generated
 */
public class DaoFactoryImpl extends DaoFactory.Factory {
    public RequisitionDao createRequisitionDao( Connection conn ) {
        return new RequisitionDaoImpl( conn );
    }

	@Override
	public BrugerDao createBrugerDao(Connection conn) {
		return new BrugerDaoImpl(conn);
	}
	
	public CtKontrolDao createCtKontrolDao( Connection conn ) {
        return new CtKontrolDaoImpl( conn );
    }
	 public MrKontrolDao createMrKontrolDao( Connection conn ) {
	        return new MrKontrolDaoImpl( conn );
	    }
	 public PatientDao createPatientDao( Connection conn ) {
	        return new PatientDaoImpl( conn );
	    }
	 public PetctKontrolskemaDao createPetctKontrolskemaDao( Connection conn ) {
	        return new PetctKontrolskemaDaoImpl( conn );
	    }
	 public RettighederDao createRettighederDao( Connection conn ) {
	        return new RettighederDaoImpl( conn );
	    }
	 public UndersoegelsesTypeDao createUndersoegelsesTypeDao( Connection conn ) {
	        return new UndersoegelsesTypeDaoImpl( conn );
	    }
	 public RegisteredUserDao createRegisteredUserDao( Connection conn ) {
	        return new RegisteredUserDaoImpl( conn );
	    }

}
