/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package database.dao.mysql;


import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.sql.Types;

import java.util.ArrayList;

import com.spoledge.audao.db.dao.AbstractDaoImpl;
import com.spoledge.audao.db.dao.DBException;
import com.spoledge.audao.db.dao.DaoException;


import database.dao.PatientDao;
import database.dto.Patient;


/**
 * This is the DAO imlementation class.
 *
 * @author generated
 */
public class PatientDaoImpl extends AbstractDaoImpl<Patient> implements PatientDao {

    private static final String TABLE_NAME = "patient";

    protected static final String SELECT_COLUMNS = "cpr, foedselsdag, afdeling";

    protected static final String PK_CONDITION = "cpr=?";

    private static final String SQL_INSERT = "INSERT INTO patient (cpr,foedselsdag,afdeling) VALUES (?,?,?)";

    public PatientDaoImpl( Connection conn ) {
        super( conn );
    }

    /**
     * Finds a record identified by its primary key.
     * @return the record found or null
     */
    public Patient findByPrimaryKey( String cpr ) {
        return findOne( PK_CONDITION, cpr);
    }

    /**
     * Inserts a new record.
     */
    public void insert( Patient dto ) throws DaoException {
        PreparedStatement stmt = null;

        debugSql( SQL_INSERT, dto );

        try {
            stmt = conn.prepareStatement( SQL_INSERT );

            if ( dto.getCpr() == null ) {
                throw new DaoException("Value of column 'cpr' cannot be null");
            }
            checkMaxLength( "cpr", dto.getCpr(), 30 );
            stmt.setString( 1, dto.getCpr() );

            if ( dto.getFoedselsdag() == null ) {
                throw new DaoException("Value of column 'foedselsdag' cannot be null");
            }
            stmt.setTimestamp( 2, dto.getFoedselsdag() );

            if ( dto.getAfdeling() == null ) {
                throw new DaoException("Value of column 'afdeling' cannot be null");
            }
            checkMaxLength( "afdeling", dto.getAfdeling(), 50 );
            stmt.setString( 3, dto.getAfdeling() );

            int n = stmt.executeUpdate();
        }
        catch (SQLException e) {
            errorSql( e, SQL_INSERT, dto );
            handleException( e );
            throw new DBException( e );
        }
        finally {
            if (stmt != null) try { stmt.close(); } catch (SQLException e) {}
        }
    }

    /**
     * Returns the table name.
     */
    public String getTableName() {
        return TABLE_NAME;
    }

    protected String getSelectColumns() {
        return SELECT_COLUMNS;
    }

    protected Patient fetch( ResultSet rs ) throws SQLException {
        Patient dto = new Patient();
        dto.setCpr( rs.getString( 1 ));
        dto.setFoedselsdag( rs.getTimestamp( 2 ));
        dto.setAfdeling( rs.getString( 3 ));

        return dto;
    }

    protected Patient[] toArray(ArrayList<Patient> list ) {
        Patient[] ret = new Patient[ list.size() ];
        return list.toArray( ret );
    }

}
