/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package dto;

import java.sql.Timestamp;

import com.spoledge.audao.db.dto.AbstractDto;

/**
 * This is a DTO class.
 *
 * @author generated
 */
public class MrKontrol extends AbstractDto {

    ////////////////////////////////////////////////////////////////////////////
    // Static
    ////////////////////////////////////////////////////////////////////////////

    public static final String TABLE = "mr_kontrol";

    ////////////////////////////////////////////////////////////////////////////
    // Attributes
    ////////////////////////////////////////////////////////////////////////////
    
    private Integer ctKontrastKontrolskemaId;
    private Boolean diabetes;
    private Boolean nyrefunktion;
    private Boolean nyreopereret;
    private Boolean hjertesygdom;
    private Boolean myokarieinfarkt;
    private Boolean proteinuri;
    private Boolean urinsyregigt;
    private Boolean over70;
    private Boolean hypertension;
    private Boolean nsaidPraeparat;
    private Boolean aminoglykosider;
    private Boolean allergi;
    private Boolean kontraststofreaktion;
    private Boolean astma;
    private Boolean hyperthyreoidisme;
    private Boolean metformin;
    private Boolean interleukin2;
    private Boolean betaBlokkere;
    private String pKreatinVaerdi;
    private Timestamp pKreatinTimestamp;
    private Integer ptHoejde;
    private Integer ptVaegt;

    ////////////////////////////////////////////////////////////////////////////
    // Constructors
    ////////////////////////////////////////////////////////////////////////////

    /**
     * Creates a new empty DTO.
     */
    public MrKontrol() {
    }

    ////////////////////////////////////////////////////////////////////////////
    // Public
    ////////////////////////////////////////////////////////////////////////////

    public Integer getCtKontrastKontrolskemaId() {
        return ctKontrastKontrolskemaId;
    }

    public void setCtKontrastKontrolskemaId( Integer _val) {
        this.ctKontrastKontrolskemaId = _val;
    }

    public Boolean getDiabetes() {
        return diabetes;
    }

    public void setDiabetes( Boolean _val) {
        this.diabetes = _val;
    }

    public Boolean getNyrefunktion() {
        return nyrefunktion;
    }

    public void setNyrefunktion( Boolean _val) {
        this.nyrefunktion = _val;
    }

    public Boolean getNyreopereret() {
        return nyreopereret;
    }

    public void setNyreopereret( Boolean _val) {
        this.nyreopereret = _val;
    }

    public Boolean getHjertesygdom() {
        return hjertesygdom;
    }

    public void setHjertesygdom( Boolean _val) {
        this.hjertesygdom = _val;
    }

    public Boolean getMyokarieinfarkt() {
        return myokarieinfarkt;
    }

    public void setMyokarieinfarkt( Boolean _val) {
        this.myokarieinfarkt = _val;
    }

    public Boolean getProteinuri() {
        return proteinuri;
    }

    public void setProteinuri( Boolean _val) {
        this.proteinuri = _val;
    }

    public Boolean getUrinsyregigt() {
        return urinsyregigt;
    }

    public void setUrinsyregigt( Boolean _val) {
        this.urinsyregigt = _val;
    }

    public Boolean getOver70() {
        return over70;
    }

    public void setOver70( Boolean _val) {
        this.over70 = _val;
    }

    public Boolean getHypertension() {
        return hypertension;
    }

    public void setHypertension( Boolean _val) {
        this.hypertension = _val;
    }

    public Boolean getNsaidPraeparat() {
        return nsaidPraeparat;
    }

    public void setNsaidPraeparat( Boolean _val) {
        this.nsaidPraeparat = _val;
    }

    public Boolean getAminoglykosider() {
        return aminoglykosider;
    }

    public void setAminoglykosider( Boolean _val) {
        this.aminoglykosider = _val;
    }

    public Boolean getAllergi() {
        return allergi;
    }

    public void setAllergi( Boolean _val) {
        this.allergi = _val;
    }

    public Boolean getKontraststofreaktion() {
        return kontraststofreaktion;
    }

    public void setKontraststofreaktion( Boolean _val) {
        this.kontraststofreaktion = _val;
    }

    public Boolean getAstma() {
        return astma;
    }

    public void setAstma( Boolean _val) {
        this.astma = _val;
    }

    public Boolean getHyperthyreoidisme() {
        return hyperthyreoidisme;
    }

    public void setHyperthyreoidisme( Boolean _val) {
        this.hyperthyreoidisme = _val;
    }

    public Boolean getMetformin() {
        return metformin;
    }

    public void setMetformin( Boolean _val) {
        this.metformin = _val;
    }

    public Boolean getInterleukin2() {
        return interleukin2;
    }

    public void setInterleukin2( Boolean _val) {
        this.interleukin2 = _val;
    }

    public Boolean getBetaBlokkere() {
        return betaBlokkere;
    }

    public void setBetaBlokkere( Boolean _val) {
        this.betaBlokkere = _val;
    }

    public String getPKreatinVaerdi() {
        return pKreatinVaerdi;
    }

    public void setPKreatinVaerdi( String _val) {
        this.pKreatinVaerdi = _val;
    }

    public Timestamp getPKreatinTimestamp() {
        return pKreatinTimestamp;
    }

    public void setPKreatinTimestamp( java.util.Date _val ) {
        setPKreatinTimestamp((Timestamp)( _val != null ? new Timestamp( _val.getTime()) : null ));
    }

    public void setPKreatinTimestamp( Timestamp _val) {
        this.pKreatinTimestamp = _val;
    }

    public Integer getPtHoejde() {
        return ptHoejde;
    }

    public void setPtHoejde( Integer _val) {
        this.ptHoejde = _val;
    }

    public Integer getPtVaegt() {
        return ptVaegt;
    }

    public void setPtVaegt( Integer _val) {
        this.ptVaegt = _val;
    }

    /**
     * Indicates whether some other object is "equal to" this one.
     * Uses 'columns' equality type.
     */
    @Override
    public boolean equals( Object _other ) {
        if (_other == this) return true;
        if (_other == null || (!(_other instanceof MrKontrol))) return false;

        MrKontrol _o = (MrKontrol) _other;

        if ( ctKontrastKontrolskemaId == null ) {
            if ( _o.ctKontrastKontrolskemaId != null ) return false;
        }
        else if ( _o.ctKontrastKontrolskemaId == null || ctKontrastKontrolskemaId.intValue() != _o.ctKontrastKontrolskemaId.intValue()) return false;

        if ( diabetes == null ) {
            if ( _o.diabetes != null ) return false;
        }
        else if ( _o.diabetes == null || diabetes.booleanValue() != _o.diabetes.booleanValue()) return false;

        if ( nyrefunktion == null ) {
            if ( _o.nyrefunktion != null ) return false;
        }
        else if ( _o.nyrefunktion == null || nyrefunktion.booleanValue() != _o.nyrefunktion.booleanValue()) return false;

        if ( nyreopereret == null ) {
            if ( _o.nyreopereret != null ) return false;
        }
        else if ( _o.nyreopereret == null || nyreopereret.booleanValue() != _o.nyreopereret.booleanValue()) return false;

        if ( hjertesygdom == null ) {
            if ( _o.hjertesygdom != null ) return false;
        }
        else if ( _o.hjertesygdom == null || hjertesygdom.booleanValue() != _o.hjertesygdom.booleanValue()) return false;

        if ( myokarieinfarkt == null ) {
            if ( _o.myokarieinfarkt != null ) return false;
        }
        else if ( _o.myokarieinfarkt == null || myokarieinfarkt.booleanValue() != _o.myokarieinfarkt.booleanValue()) return false;

        if ( proteinuri == null ) {
            if ( _o.proteinuri != null ) return false;
        }
        else if ( _o.proteinuri == null || proteinuri.booleanValue() != _o.proteinuri.booleanValue()) return false;

        if ( urinsyregigt == null ) {
            if ( _o.urinsyregigt != null ) return false;
        }
        else if ( _o.urinsyregigt == null || urinsyregigt.booleanValue() != _o.urinsyregigt.booleanValue()) return false;

        if ( over70 == null ) {
            if ( _o.over70 != null ) return false;
        }
        else if ( _o.over70 == null || over70.booleanValue() != _o.over70.booleanValue()) return false;

        if ( hypertension == null ) {
            if ( _o.hypertension != null ) return false;
        }
        else if ( _o.hypertension == null || hypertension.booleanValue() != _o.hypertension.booleanValue()) return false;

        if ( nsaidPraeparat == null ) {
            if ( _o.nsaidPraeparat != null ) return false;
        }
        else if ( _o.nsaidPraeparat == null || nsaidPraeparat.booleanValue() != _o.nsaidPraeparat.booleanValue()) return false;

        if ( aminoglykosider == null ) {
            if ( _o.aminoglykosider != null ) return false;
        }
        else if ( _o.aminoglykosider == null || aminoglykosider.booleanValue() != _o.aminoglykosider.booleanValue()) return false;

        if ( allergi == null ) {
            if ( _o.allergi != null ) return false;
        }
        else if ( _o.allergi == null || allergi.booleanValue() != _o.allergi.booleanValue()) return false;

        if ( kontraststofreaktion == null ) {
            if ( _o.kontraststofreaktion != null ) return false;
        }
        else if ( _o.kontraststofreaktion == null || kontraststofreaktion.booleanValue() != _o.kontraststofreaktion.booleanValue()) return false;

        if ( astma == null ) {
            if ( _o.astma != null ) return false;
        }
        else if ( _o.astma == null || astma.booleanValue() != _o.astma.booleanValue()) return false;

        if ( hyperthyreoidisme == null ) {
            if ( _o.hyperthyreoidisme != null ) return false;
        }
        else if ( _o.hyperthyreoidisme == null || hyperthyreoidisme.booleanValue() != _o.hyperthyreoidisme.booleanValue()) return false;

        if ( metformin == null ) {
            if ( _o.metformin != null ) return false;
        }
        else if ( _o.metformin == null || metformin.booleanValue() != _o.metformin.booleanValue()) return false;

        if ( interleukin2 == null ) {
            if ( _o.interleukin2 != null ) return false;
        }
        else if ( _o.interleukin2 == null || interleukin2.booleanValue() != _o.interleukin2.booleanValue()) return false;

        if ( betaBlokkere == null ) {
            if ( _o.betaBlokkere != null ) return false;
        }
        else if ( _o.betaBlokkere == null || betaBlokkere.booleanValue() != _o.betaBlokkere.booleanValue()) return false;

        if ( pKreatinVaerdi == null ) {
            if ( _o.pKreatinVaerdi != null ) return false;
        }
        else if ( _o.pKreatinVaerdi == null || !pKreatinVaerdi.equals( _o.pKreatinVaerdi )) return false;

        if ( pKreatinTimestamp == null ) {
            if ( _o.pKreatinTimestamp != null ) return false;
        }
        else if ( _o.pKreatinTimestamp == null || pKreatinTimestamp.getTime() != _o.pKreatinTimestamp.getTime()) return false;

        if ( ptHoejde == null ) {
            if ( _o.ptHoejde != null ) return false;
        }
        else if ( _o.ptHoejde == null || ptHoejde.intValue() != _o.ptHoejde.intValue()) return false;

        if ( ptVaegt == null ) {
            if ( _o.ptVaegt != null ) return false;
        }
        else if ( _o.ptVaegt == null || ptVaegt.intValue() != _o.ptVaegt.intValue()) return false;

        return true;
    }

    /**
     * Returns a hash code value for the object.
     */
    @Override
    public int hashCode() {
        int _ret = 503133664; // = "MrKontrol".hashCode()
        _ret += ctKontrastKontrolskemaId == null ? 0 : ctKontrastKontrolskemaId;
        _ret = 29 * _ret + (diabetes == null ? 0 : (diabetes ? 1 : 0));
        _ret = 29 * _ret + (nyrefunktion == null ? 0 : (nyrefunktion ? 1 : 0));
        _ret = 29 * _ret + (nyreopereret == null ? 0 : (nyreopereret ? 1 : 0));
        _ret = 29 * _ret + (hjertesygdom == null ? 0 : (hjertesygdom ? 1 : 0));
        _ret = 29 * _ret + (myokarieinfarkt == null ? 0 : (myokarieinfarkt ? 1 : 0));
        _ret = 29 * _ret + (proteinuri == null ? 0 : (proteinuri ? 1 : 0));
        _ret = 29 * _ret + (urinsyregigt == null ? 0 : (urinsyregigt ? 1 : 0));
        _ret = 29 * _ret + (over70 == null ? 0 : (over70 ? 1 : 0));
        _ret = 29 * _ret + (hypertension == null ? 0 : (hypertension ? 1 : 0));
        _ret = 29 * _ret + (nsaidPraeparat == null ? 0 : (nsaidPraeparat ? 1 : 0));
        _ret = 29 * _ret + (aminoglykosider == null ? 0 : (aminoglykosider ? 1 : 0));
        _ret = 29 * _ret + (allergi == null ? 0 : (allergi ? 1 : 0));
        _ret = 29 * _ret + (kontraststofreaktion == null ? 0 : (kontraststofreaktion ? 1 : 0));
        _ret = 29 * _ret + (astma == null ? 0 : (astma ? 1 : 0));
        _ret = 29 * _ret + (hyperthyreoidisme == null ? 0 : (hyperthyreoidisme ? 1 : 0));
        _ret = 29 * _ret + (metformin == null ? 0 : (metformin ? 1 : 0));
        _ret = 29 * _ret + (interleukin2 == null ? 0 : (interleukin2 ? 1 : 0));
        _ret = 29 * _ret + (betaBlokkere == null ? 0 : (betaBlokkere ? 1 : 0));
        _ret = 29 * _ret + (pKreatinVaerdi == null ? 0 : pKreatinVaerdi.hashCode());
        _ret = 29 * _ret + (pKreatinTimestamp == null ? 0 : (int)pKreatinTimestamp.getTime());
        _ret = 29 * _ret + (ptHoejde == null ? 0 : ptHoejde);
        _ret = 29 * _ret + (ptVaegt == null ? 0 : ptVaegt);

        return _ret;
    }


    ////////////////////////////////////////////////////////////////////////////
    // Protected
    ////////////////////////////////////////////////////////////////////////////
		
    /**
     * Constructs the content for the toString() method.
     */
    protected void contentToString(StringBuffer sb) {
        append( sb, "ctKontrastKontrolskemaId", ctKontrastKontrolskemaId );
        append( sb, "diabetes", diabetes );
        append( sb, "nyrefunktion", nyrefunktion );
        append( sb, "nyreopereret", nyreopereret );
        append( sb, "hjertesygdom", hjertesygdom );
        append( sb, "myokarieinfarkt", myokarieinfarkt );
        append( sb, "proteinuri", proteinuri );
        append( sb, "urinsyregigt", urinsyregigt );
        append( sb, "over70", over70 );
        append( sb, "hypertension", hypertension );
        append( sb, "nsaidPraeparat", nsaidPraeparat );
        append( sb, "aminoglykosider", aminoglykosider );
        append( sb, "allergi", allergi );
        append( sb, "kontraststofreaktion", kontraststofreaktion );
        append( sb, "astma", astma );
        append( sb, "hyperthyreoidisme", hyperthyreoidisme );
        append( sb, "metformin", metformin );
        append( sb, "interleukin2", interleukin2 );
        append( sb, "betaBlokkere", betaBlokkere );
        append( sb, "pKreatinVaerdi", pKreatinVaerdi );
        append( sb, "pKreatinTimestamp", pKreatinTimestamp );
        append( sb, "ptHoejde", ptHoejde );
        append( sb, "ptVaegt", ptVaegt );
    }
}
